-- Migration: phase2_review_flow_and_planning
-- Version:  20260714232504
--
-- This migration was applied directly to the live Supabase project before being
-- recorded here. This file documents the resulting schema so the repo has a
-- record of it. It is written idempotently (IF NOT EXISTS / guarded ADDs) so it
-- is safe to keep as a record and will not re-apply or alter the live schema.

-- ── content_library — review / approve / push workflow columns ───────────────
alter table public.content_library add column if not exists status                text not null default 'draft';
alter table public.content_library add column if not exists edited_content        text;
alter table public.content_library add column if not exists approved_at           timestamptz;
alter table public.content_library add column if not exists blotato_submission_id text;
alter table public.content_library add column if not exists scheduled_for         timestamptz;
alter table public.content_library add column if not exists push_error            text;

-- Allowed status values are enforced by a check constraint. Use these strings
-- exactly — anything else fails on write:
--   draft, approved, approved_needs_media, rejected, pushed, failed
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'content_library_status_check') then
    alter table public.content_library
      add constraint content_library_status_check
      check (status = any (array['draft'::text, 'approved'::text, 'approved_needs_media'::text,
                                 'rejected'::text, 'pushed'::text, 'failed'::text]));
  end if;
end $$;

-- Index for the review view (list a week's rows by status).
create index if not exists content_library_week_status_idx
  on public.content_library using btree (week_commencing, status);

-- ── weekly_plan — source of truth for the weekly content plan ────────────────
-- sites shape: { "<siteId>": { "pillarId": "...", "theme": "...", "notes": "..." } }
create table if not exists public.weekly_plan (
  week_commencing    date primary key,
  campaign_objective text,
  set_at             timestamptz not null default now(),
  sites              jsonb not null
);

-- ── research_briefs — optional per-site research brief for a week ─────────────
create table if not exists public.research_briefs (
  id              bigint generated by default as identity primary key,
  site_id         text not null,
  week_commencing date not null,
  brief           text not null,
  source          text not null default 'cowork',
  created_at      timestamptz not null default now(),
  unique (site_id, week_commencing)
);

-- Access notes (recorded, not re-applied here):
--   * content_library keeps the RLS + anon read/write/update policies from the
--     create_content_library migration.
--   * weekly_plan and research_briefs are created without RLS; the anon and
--     authenticated roles hold full table grants (Supabase default), so the Hub
--     (anon key) can read and upsert them.
